
name: cohort_metrics
version: '1.0'
config-version: 2
profile: cohort_metrics

model-paths: ["models"]
target-path: "target"

models:
  cohort_metrics:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: table

