
services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Optional: for direct DB access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  airflow-init:
    build:
      context: .
      dockerfile: airflow.Dockerfile
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=mainya08
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./airflow_data:/opt/airflow
      - ./logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env:ro
      - ./scripts:/opt/airflow/scripts
      - ./source:/opt/airflow/source
    command: |
      bash -c "
      airflow db init &&
      airflow users create \
        --username admin \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email jumaochi1@gmail.com \
        --password admin
      "
    restart: "no"  # Only run once for initialization

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow.Dockerfile
    container_name: airflow_scheduler
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key_here_change_this
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./airflow_data:/opt/airflow
      - ./logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env:ro
      - ./scripts:/opt/airflow/scripts
      - ./source:/opt/airflow/source 
    command: airflow scheduler
    restart: always

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow.Dockerfile
    container_name: airflow_webserver
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key_here_change_this
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./airflow_data:/opt/airflow
      - ./logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env:ro
      - ./scripts:/opt/airflow/scripts
      - ./source:/opt/airflow/source 
    ports:
      - "8080:8080"
    command: airflow webserver
    restart: always

volumes:
  postgres_data: